info:
  contact: {}
paths:
  /health:
    get:
      description: healthcheck
      produces:
      - application/json
      responses: {}
      summary: healthcheck
      tags:
      - health
swagger: "2.0"
